import java.util.Random;

public class PolicyException extends Exception{
    int ID;
    public PolicyException(int ID) throws PolicyException {
        if(String.valueOf(ID).length() != 6 || String.valueOf(ID).charAt(0) == '3') {
            this.ID = generateRandomID();
            throw new PolicyException(this.ID);
        }
    }

    @Override
    public String toString() {
        return "The Policy ID was not valid and a new ID " + this.ID + " is generated by admin" +
                " and assigned for the Policy";
    }

    public int generateRandomID() {
        Random random = new Random();
        int low = 300000;
        int high = 399999;
        return random.nextInt(high-low) + low;
    }
}

