
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erfan
 */
public class UpdatePanel extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePanel
     */
    private InsurancePolicy policy;
    private UserPanel adminPanel;
    public UpdatePanel(InsurancePolicy policy, UserPanel adminPanel) {
        this.policy = policy;
        this.adminPanel = adminPanel;
        initComponents();
        System.out.println(policy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        thirdPartyRadioButton = new javax.swing.JRadioButton();
        comprehensiveRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        policyIDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        policyHolderNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        carModelField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        carTypeComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        manufacturingYearField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        carPriceField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numberOfClaimsField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dateYearField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dateMonthField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dateDayField = new javax.swing.JTextField();
        commentAndDriverAgeLabel = new javax.swing.JLabel();
        commentAndDriverAgeField = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        levelField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        clearPlansClearBtn = new javax.swing.JButton();
        updatePlansAddBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(thirdPartyRadioButton);
        thirdPartyRadioButton.setSelected(true);
        thirdPartyRadioButton.setText("Third Party");
        thirdPartyRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thirdPartyRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(comprehensiveRadioButton);
        comprehensiveRadioButton.setText("Comprehensive");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Policy ID");

        policyIDField.setEditable(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Policy holder name");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Car");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Car Model");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Car Type");

        carTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        CarType[] carTypes = CarType.values();
        for(CarType carType : carTypes) {
            carTypeComboBox.addItem(carType.toString());
        }
        carTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Manufacturing Year");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Car Price");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("No. of Claims");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Date");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Year");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Month");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Day");

        commentAndDriverAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        commentAndDriverAgeLabel.setText("Comment");

        commentAndDriverAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentAndDriverAgeFieldActionPerformed(evt);
            }
        });

        levelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        levelLabel.setText("Level");

        levelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelFieldActionPerformed(evt);
            }
        });

        clearPlansClearBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearPlansClearBtn.setForeground(new java.awt.Color(255, 0, 0));
        clearPlansClearBtn.setText("Clear");
        clearPlansClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPlansClearBtnActionPerformed(evt);
            }
        });

        updatePlansAddBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updatePlansAddBtn.setForeground(new java.awt.Color(255, 0, 0));
        updatePlansAddBtn.setText("Update");
        updatePlansAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlansAddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(updatePlansAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearPlansClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearPlansClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePlansAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        policyIDField.setText(Integer.toString(this.policy.getPolicyID()));
        policyHolderNameField.setText(this.policy.getPolicyHolderName());
        Car car = this.policy.getCar();
        carModelField.setText(car.getModel());
        carTypeComboBox.setSelectedItem(car.getType().toString());
        manufacturingYearField.setText(Integer.toString(car.getManufacturingYear()));
        carPriceField.setText(Double.toString(car.getPrice()));
        numberOfClaimsField.setText(Integer.toString(this.policy.getNumberOfClaims()));
        MyDate date = this.policy.getExpiryDate();
        dateYearField.setText(Integer.toString(date.getYear()));
        dateMonthField.setText(Integer.toString(date.getMonth()));
        dateDayField.setText(Integer.toString(date.getDay()));
        if(this.policy instanceof ThirdPartyInsurancePolicy) {
            thirdPartyRadioButton.setSelected(true);
            comprehensiveRadioButton.setSelected(false);
            commentAndDriverAgeField.setText(((ThirdPartyInsurancePolicy) policy).getComments());
            commentAndDriverAgeLabel.setText("Comment");
            levelField.setVisible(false);
            levelLabel.setVisible(false);
        } else {
            thirdPartyRadioButton.setSelected(false);
            comprehensiveRadioButton.setSelected(true);
            commentAndDriverAgeField.setText(Integer.toString(((ComprehensiveInsurancePolicy) this.policy).getDriverAge()));
            commentAndDriverAgeLabel.setText("Driver Age");
            levelField.setVisible(true);
            levelLabel.setVisible(true);
            levelField.setText(Integer.toString(((ComprehensiveInsurancePolicy) this.policy).getLevel()));
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thirdPartyRadioButton)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comprehensiveRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(policyIDField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(policyHolderNameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carModelField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manufacturingYearField)
                    .addComponent(carPriceField)
                    .addComponent(numberOfClaimsField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateYearField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateMonthField)
                    .addComponent(dateDayField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commentAndDriverAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(commentAndDriverAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(levelField))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdPartyRadioButton)
                    .addComponent(comprehensiveRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(commentAndDriverAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(commentAndDriverAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(policyIDField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(policyHolderNameField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carModelField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturingYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfClaimsField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thirdPartyRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thirdPartyRadioButtonStateChanged
        // TODO add your handling code here:
        if(thirdPartyRadioButton.isSelected()) {
            commentAndDriverAgeLabel.setText("Comment");
            levelLabel.setVisible(false);
            levelField.setVisible(false);
        } else {
            commentAndDriverAgeLabel.setText("Driver Age");
            levelLabel.setVisible(true);
            levelField.setVisible(true);
        }
    }//GEN-LAST:event_thirdPartyRadioButtonStateChanged

    private void carTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypeComboBoxActionPerformed

    private void commentAndDriverAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentAndDriverAgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentAndDriverAgeFieldActionPerformed

    private void levelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelFieldActionPerformed

    private void clearPlansClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPlansClearBtnActionPerformed
        // TODO add your handling code here:
        policyIDField.setText("");
        policyHolderNameField.setText("");
        carModelField.setText("");
        manufacturingYearField.setText("");
        carPriceField.setText("");
        numberOfClaimsField.setText("");
        dateYearField.setText("");
        dateMonthField.setText("");
        dateDayField.setText("");
        commentAndDriverAgeField.setText("");
    }//GEN-LAST:event_clearPlansClearBtnActionPerformed

    private void updatePlansAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlansAddBtnActionPerformed
        // TODO add your handling code here:
        try {
            String carModel = carModelField.getText();
            String policyHolderName = policyHolderNameField.getText();
            CarType carType = CarType.valueOf(carTypeComboBox.getSelectedItem().toString());
            int manufacturingYear = Integer.parseInt(manufacturingYearField.getText());
            double carPrice = Double.parseDouble(carPriceField.getText());
            Car car = new Car(carModel, carType, manufacturingYear, carPrice);
            int numOfClaims = Integer.parseInt(numberOfClaimsField.getText());
            int dateYear = Integer.parseInt(dateYearField.getText());
            int dateMonth = Integer.parseInt(dateMonthField.getText());
            int dateDay = Integer.parseInt(dateDayField.getText());
            MyDate date = new MyDate(dateYear, dateMonth, dateDay);
            String commentAndDriverAge = commentAndDriverAgeField.getText();
            int level = Integer.parseInt(levelField.getText());
            if(updatePlansAddBtn.getText() == "Update") {
                this.policy.setPolicyHolderName(policyHolderName);
                this.policy.setCar(car);
                this.policy.setNumberOfClaims(numOfClaims); 
                this.policy.setExpiryDate(date);
                if(thirdPartyRadioButton.isSelected()) {
                    ((ThirdPartyInsurancePolicy) this.policy).setComments(commentAndDriverAge);
                } else {
                    ((ComprehensiveInsurancePolicy) this.policy).setDriverAge(Integer.parseInt(commentAndDriverAge));
                    ((ComprehensiveInsurancePolicy) this.policy).setLevel(level);
                }
                JOptionPane.showMessageDialog(this, "Policy Updated Successfully!");
                this.adminPanel.fillTable();
                this.dispose();
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_updatePlansAddBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdatePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdatePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdatePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdatePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdatePanel().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carModelField;
    private javax.swing.JTextField carPriceField;
    private javax.swing.JComboBox<String> carTypeComboBox;
    private javax.swing.JButton clearPlansClearBtn;
    private javax.swing.JTextField commentAndDriverAgeField;
    private javax.swing.JLabel commentAndDriverAgeLabel;
    private javax.swing.JRadioButton comprehensiveRadioButton;
    private javax.swing.JTextField dateDayField;
    private javax.swing.JTextField dateMonthField;
    private javax.swing.JTextField dateYearField;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField manufacturingYearField;
    private javax.swing.JTextField numberOfClaimsField;
    private javax.swing.JTextField policyHolderNameField;
    private javax.swing.JTextField policyIDField;
    private javax.swing.JRadioButton thirdPartyRadioButton;
    private javax.swing.JButton updatePlansAddBtn;
    // End of variables declaration//GEN-END:variables
}
